spring:
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com/xjhxkqaj?currentSchema=site
    password: lHtqou4E6-pG6kZSHEic-ZpWntmKdiA5
    username: xjhxkqaj